name: Node.js Package
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
      
    steps:
      - uses: actions/checkout@v2
 
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 14
          
 
      - run: npm install
      - run: |
          npm i
          npm run build
          echo //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }} >>.npmrc         
          npm publish --access public
